- match:
    dependency_type: "development"
    update_type: "all"
- match:
    dependency_type: "production"
    update_type: "semver:patch"
- match:
    dependency_name: "specinfra"
    update_type: "all"
- match:
    dependency_name: "rspec*"
    update_type: "all"
